### ISSUE TITLE
Model Research( NMF )

### ISSUE THREAD

**Issue by prezmora** [AML-2304-NaturalLanguageProcessing/AmazonBooksRecommendation#43]
Non-Negative Matrix Factorization (NMF) is a linear algebra algorithm used to uncover hidden topics by decomposing high-dimensional vectors into non-negative, lower-dimensional representations.

**Comment by floramaevillarin** [comment]
Non-Negative Matrix Factorization (NMF) is a linear algebra algorithm used to uncover hidden topics by decomposing high-dimensional vectors into non-negative, lower-dimensional representations.  
https://medium.com/blend360/introduction-to-topic-modelling-with-lda-nmf-top2vec-and-bertopic-ffc3624d44e4

NMF works on TF-IDF transformed data by breaking down a matrix into two lower-ranking matrices
https://www.frontiersin.org/journals/sociology/articles/10.3389/fsoc.2022.886498/full

Sample code using TF-IDF transformed data. 
[non-negative-matrix-factorization-tfidf.zip](https://github.com/user-attachments/files/16121690/non-negative-matrix-factorization-tfidf.zip)

In Progress - currently exploring the NMF using word2vec-transformed data.
