### ISSUE TITLE
Set up Azure Cosmos MongoDB

### ISSUE THREAD

**Issue by prezmora** [AML-2304-NaturalLanguageProcessing/AmazonBooksRecommendation#44]

**Comment by floramaevillarin** [comment]
Database: AmazonBooksReviews

Following collections:
  raw_reviews
  raw_books
  cleaned_reviews
  cleaned_books
  final_reviews
  final_books

May use Azure Data Studio  to manage the DB - https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?tabs=win-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall

ConnectionString; mongodb://amlnlp:Y08RC33AbnX2t6hEWS7vDBo6oD9dsNiafrC8UzD2CXtkYv9ZbfBW8dehrDFuw3SSeuI1GgPjXF7gACDb8dz8qw==@amlnlp.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@amlnlp@
